### PR TITLE
Classification

### PR DESCRIPTION
**Pull request by jmirtsch**
At the moment Classification Title is detected for Uniformat but not OmniClass.  This commit enables OmniClass in the same manner.

### CODE REVIEW

**Comment by tsolsen** [comment]
If I read the pull correctly, you are suggesting implementing either Uni OR Omniclass as the classification name. Many don't use either, and have the same problem with the Uniclass Title text.
Would it not be more correct, to bypass the Uniclass Title altogether, and look directly at the label in Classification Settings: Name?

**Comment by jmirtsch** [comment]
Hi Troels,

See if this clarifies the code change request.  My use case is very much to enable use of other classification systems, certainly I believe the implementation in Revit could be improved a lot to facilitate this.  Some of my recent work, I believe it's convenient to use the assembly code parameter in revit to nominate classification reference  in other systems.  Here is a uniclass2015 example.  
https://drive.google.com/file/d/1k9NgzGDNc0uBV14iCEV8Vh3Wj7c_sYDo/view?usp=sharing
You can generate the uniclass assembly code input text file for Revit from my ggRevitIFC plugin.  This can automate the inclusion of the classification description parameter.  In this scenario, I don't want any reference to OmniClass in the resulting IFC file.

See if these images explain, let me know any aspect that isn't clear.  This pull request should have no effect if you are using OmniClass specifically.

181108 uniclass assembly code ifc
181108 uniclass assembly code


Cheers,

Jon

**Comment by tsolsen** [comment]
It does. I misunderstood the pull, reading it as you where going after Uni OR Omni, not fixing the Assembly Code problem. Super.

Actually I implemented Assembly Code as classification when it came out (2015?). But it does not cover our needs. We have 5+ systems, that can/will come into play - and assembly code only supports 1. Supporting that in "Classification" parameters is obviously a hassle.

image

At one point in time, several things are needed:
- A proper ootb classification module, that supports n+1 systems
- IfcClassification parameters for each system, as we have in the exporter today, in that module.
- Each system adds a Assembly Code style tree structure (shared) parameter.

**Comment by epeter-** [comment]
Jon, the assignment of classification is working as expected.
unfortunately the  name of the classification is alway set to default. User input is ignored.
image

**Pull request merged**
